#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG="/usr/bin/dufs"

append_cmd() {
	procd_append_param command "$@"
}

append_flagged_value() {
	local value="$1"
	local flag="$2"
	[ -n "$value" ] && append_cmd "$flag" "$value"
}

append_raw_value() {
	local value="$1"
	[ -n "$value" ] && append_cmd "$value"
}

append_bool_flag() {
	local cfg="$1"
	local key="$2"
	local flag="$3"
	local def="${4:-0}"
	local enabled

	config_get_bool enabled "$cfg" "$key" "$def"
	[ "$enabled" -eq 1 ] && append_cmd "$flag"
}

append_value_flag() {
	local cfg="$1"
	local key="$2"
	local flag="$3"
	local def="$4"
	local value

	config_get value "$cfg" "$key" "$def"
	[ -n "$value" ] && append_cmd "$flag" "$value"
}

start_instance() {
	local cfg="$1"
	local enabled serve_path user group

	config_get_bool enabled "$cfg" enabled 0
	[ "$enabled" -eq 1 ] || return 0

	config_get serve_path "$cfg" serve_path "/mnt"
	config_get user "$cfg" user "root"
	config_get group "$cfg" group "root"

	[ -x "$PROG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG"

	config_list_foreach "$cfg" bind append_flagged_value --bind
	append_value_flag "$cfg" port --port "5000"
	append_value_flag "$cfg" path_prefix --path-prefix ""
	config_list_foreach "$cfg" hidden append_flagged_value --hidden
	config_list_foreach "$cfg" auth append_flagged_value --auth

	append_bool_flag "$cfg" allow_all --allow-all
	append_bool_flag "$cfg" allow_upload --allow-upload
	append_bool_flag "$cfg" allow_delete --allow-delete
	append_bool_flag "$cfg" allow_search --allow-search
	append_bool_flag "$cfg" allow_symlink --allow-symlink
	append_bool_flag "$cfg" allow_archive --allow-archive
	append_bool_flag "$cfg" allow_hash --allow-hash
	append_bool_flag "$cfg" enable_cors --enable-cors
	append_bool_flag "$cfg" render_index --render-index
	append_bool_flag "$cfg" render_try_index --render-try-index
	append_bool_flag "$cfg" render_spa --render-spa

	append_value_flag "$cfg" assets --assets ""
	append_value_flag "$cfg" log_format --log-format ""
	append_value_flag "$cfg" log_file --log-file ""
	append_value_flag "$cfg" compress --compress "low"
	append_value_flag "$cfg" tls_cert --tls-cert ""
	append_value_flag "$cfg" tls_key --tls-key ""

	config_list_foreach "$cfg" extra_args append_raw_value
	append_cmd "$serve_path"

	[ -n "$user" ] && procd_set_param user "$user"
	[ -n "$group" ] && procd_set_param group "$group"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

start_service() {
	config_load dufs
	config_foreach start_instance dufs
}

service_triggers() {
	procd_add_reload_trigger "dufs"
}
